name: Build
on:
  push:
    branches: [ experimental , main , dev] 
  pull_request:
    branches: [ experimental , main , dev]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
      - name: Setup solution packages
        run: dotnet restore
      - name: Build Solution
        run: dotnet build -p:Configuration=Debug;Platform=x64
      - name: Pack Test Suite
        run: tar -czvf ./PowerIO.Tests/bin/x64/Debug/TestSuite-${{github.ref}}.tar.gz ./PowerIO.Tests/bin/x64/Debug/netcoreapp2.1
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: TestSuite-${{github.ref}}
          path: ./PowerIO.Tests/bin/x64/Debug/TestSuite-${{github.ref}}.tar.gz

