name: Build-Experimental-NetCore2.1-x64
on:
  push:
    branches: [ experimental ] 
  pull_request:
    branches: [ experimental ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
      - name: Setup solution packages
        run: dotnet restore
      - name: Build Solution
        run: dotnet build -p:Configuration=Debug;Platform=x64
      - name: Pack Test Suite
        run: tar -czvf TestSuite-Experimental-NetCore2.1-x64.tar.gz --exclude=./TestSuite-Experimental-NetCore2.1-x64.tar.gz .
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: TestSuite-Experimental-NetCore2.1-x64
          path: TestSuite-Experimental-NetCore2.1-x64.tar.gz

