name: Build & Test
on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up .NET Core
        run: dotnet restore
      - name: Build Solution
        run: dotnet build
      - name: Test Solution
        run: dotnet test -v n
      
