name: Test
on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v2.1.4
        with:
          path: .
          key: build-${{ github.ref }}
