name: Test-Experimental-NetCore2.1-x64-final
on:
  workflow_run:
    workflows: ["Build-Experimental-NetCore2.1-x64"]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading TestSuite  
        uses: dawidd6/action-download-artifact@v2.13.0
        with:
          workflow: build.yml
          name: TestSuite-Experimental-NetCore2.1-x64
          path: TestSuite-Experimental-NetCore2.1-x64.tar.gz
      - name: Unpack TestSuite
        run: tar -xzvf TestSuite-Experimental-NetCore2.1-x64.tar.gz/TestSuite-Experimental-NetCore2.1-x64.tar.gz
      - name: Run Tests
        run: dotnet test -v n -p:Configuration=Debug;Platform=x64
